tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "bat"
brew "git"
brew "jenv"
brew "kafka", restart_service: true
brew "leiningen"
brew "maven", link: false
brew "maven@3.2"
brew "moreutils"
brew "node"
brew "pgcli"
brew "python"
brew "sbt"
brew "scala"
brew "telnet"
brew "tree"
brew "zsh"
brew "zsh-completions"
# Command-line fuzzy finder written in Go
brew "fzf"
cask "minishift"
