tap "caskroom/fonts"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
brew "awscli"
brew "bat"
brew "fzf"
brew "git"
brew "jenv"
brew "kafka", restart_service: true
brew "leiningen"
brew "maven", link: false
brew "maven@3.2"
brew "maven@3.5"
brew "mongodb-community", link: false
brew "mongodb-community@3.6"
brew "moreutils"
brew "nvm"
brew "pipenv"
brew "privoxy"
brew "python"
brew "sbt"
brew "scala"
brew "shellcheck"
brew "telnet"
brew "terraform"
brew "tree"
brew "zsh"
brew "zsh-completions"
cask "miniconda"
cask "minishift"
cask "caskroom/fonts/font-hack-nerd-font"
cask "dbeaver-community"
cask "copyq"