tap "caskroom/fonts"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "bat"
brew "fzf"
brew "git"
brew "jenv"
brew "kafka", restart_service: true
brew "leiningen"
brew "maven", link: false
brew "maven@3.2"
brew "maven@3.5"
brew "moreutils"
brew "node"
brew "python"
brew "sbt"
brew "scala"
brew "shellcheck"
brew "telnet"
brew "tree"
brew "zsh"
brew "zsh-completions"
cask "miniconda"
cask "minishift"
cask "caskroom/fonts/font-hack-nerd-font"
